version: '3.8'

networks:
  sandbox-network:
    driver: bridge
    internal: true  # 内部网络，不对外暴露
  user-isolated-network:
    driver: bridge
    internal: true

services:
  # 沙箱容器模板
  sandbox-template:
    image: ghcr.io/lucky-aeon/mcp-gateway:latest
    container_name: sandbox-template
    environment:
      MCP_GATEWAY_API_KEY: ${SANDBOX_API_KEY}
      SANDBOX_MODE: true
      USER_ID: ${USER_ID}
    networks:
      - user-isolated-network
    security_opt:
      - no-new-privileges:true  # 禁止特权提升
      - seccomp:unconfined  # 可配置安全计算模式
    cap_drop:
      - ALL  # 移除所有Linux capabilities
    cap_add:
      - CHOWN  # 仅允许文件所有权修改
      - SETGID
      - SETUID
    read_only: true  # 只读文件系统
    tmpfs:
      - /tmp:noexec,nosuid,size=100m  # 临时文件系统
      - /var/tmp:noexec,nosuid,size=50m
    ulimits:
      nofile:
        soft: 1024
        hard: 2048
    mem_limit: 512m  # 内存限制
    cpus: 0.5  # CPU限制
    pids_limit: 50  # 进程数限制
    restart: unless-stopped

  # 沙箱监控服务
  sandbox-monitor:
    image: prom/prometheus:latest
    container_name: sandbox-monitor
    command:
      - '--config.file=/etc/prometheus/sandbox-prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    ports:
      - "9091:9090"
    volumes:
      - ./sandbox-prometheus.yml:/etc/prometheus/sandbox-prometheus.yml:ro
      - sandbox-monitor-data:/prometheus
    networks:
      - sandbox-network
    restart: unless-stopped

  # 沙箱日志收集
  sandbox-logger:
    image: fluent/fluent-bit:latest
    container_name: sandbox-logger
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - sandbox-network
    restart: unless-stopped

volumes:
  sandbox-monitor-data:
    driver: local
