tls_server_config:
  cert_file: /etc/prometheus/certs/prometheus.crt
  key_file: /etc/prometheus/certs/prometheus.key

basic_auth_users:
  admin: $2y$10$8K1p/a0dL1LXMIgoEDFrwOfgqwAGcwZQh3UPHz9xMxqk3mKqjqKqKq
  monitor: $2y$10$9L2q/b1eM2MYNJpFEDGrxPghrxBHdxZQh4VQHz0zNzqk5nMsqjqKqKq
