version: '3.8'

networks:
  imagentx-network:
    driver: bridge

volumes:
  storage-data:
    driver: local

services:
  # Imagent X 完整服务（使用内部PostgreSQL和RabbitMQ）
  imagentx-app:
    image: ghcr.io/lucky-aeon/imagentx:latest
    container_name: imagentx-app
    environment:
      # 数据库配置 - 连接到内部PostgreSQL
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: imagentx
      DB_USER: postgres
      DB_PASSWORD: postgres
      
      # 应用配置
      SERVER_PORT: 8088
      FRONTEND_PORT: 3000
      NEXT_PUBLIC_API_BASE_URL: /api
      
      # Spring 配置
      SPRING_PROFILES_ACTIVE: docker
      JPA_DDL_AUTO: update
      SHOW_SQL: false
      
      # 用户配置
      IMAGENTX_ADMIN_EMAIL: admin@imagentx.ai
      IMAGENTX_ADMIN_PASSWORD: admin123
      IMAGENTX_ADMIN_NICKNAME: Imagent X管理员
      IMAGENTX_TEST_ENABLED: false
      IMAGENTX_TEST_EMAIL: test@imagentx.ai
      IMAGENTX_TEST_PASSWORD: test123
      IMAGENTX_TEST_NICKNAME: 测试用户
      
      # 消息队列配置 - 连接到内部RabbitMQ
      RABBITMQ_HOST: localhost
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      
      # 安全配置
      JWT_SECRET: please_change_this_in_production
      
      # 日志配置
      LOG_LEVEL_ROOT: warn
      LOG_LEVEL_APP: info
      
      # 文件存储
      FILE_STORAGE_PATH: /app/storage
      
    volumes:
      - storage-data:/app/storage
    ports:
      - "3000:3000"
      - "8088:8088"
      - "5432:5432"
      - "5672:5672"
      - "15672:15672"
    networks:
      - imagentx-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
