version: '3.8'

# macOS优化配置
services:
  postgres:
    platform: linux/arm64
    mem_limit: 2g
    cpus: 1.5
    environment:
      - POSTGRES_SHARED_PRELOAD_LIBRARIES=vector
      - POSTGRES_WORK_MEM=64MB
      - POSTGRES_MAINTENANCE_WORK_MEM=256MB
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    
  rabbitmq:
    platform: linux/arm64
    mem_limit: 1g
    cpus: 0.5
    environment:
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=0.6
    
  imagentx-backend:
    platform: linux/arm64
    mem_limit: 3g
    cpus: 2
    environment:
      - JAVA_OPTS=-XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xms1g -Xmx2g
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - storage-data:/app/storage:delegated
      - ./logs:/app/logs:delegated
    ports:
      - "8088:8088"
      - "5005:5005"
    
  imagentx-frontend:
    platform: linux/arm64
    mem_limit: 1g
    cpus: 1
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1

volumes:
  postgres-data:
    driver: local
  storage-data:
    driver: local
