# Imagent X 生产环境 Docker Compose 配置
# 使用预构建镜像，无需源码

networks:
  imagentx-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  rabbitmq-data:
    driver: local
  storage-data:
    driver: local

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: imagentx-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-imagentx}
      POSTGRES_USER: ${DB_USER:-imagentx_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-imagentx_pass}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - imagentx-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-imagentx_user} -d ${DB_NAME:-imagentx}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ 消息队列
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: imagentx-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    networks:
      - imagentx-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Imagent X 应用服务（使用预构建镜像）
  imagentx:
    image: ghcr.io/lucky-aeon/imagentx:${IMAGE_TAG:-latest}
    container_name: imagentx-app
    environment:
      # 数据库配置
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-imagentx}
      DB_USER: ${DB_USER:-imagentx_user}
      DB_PASSWORD: ${DB_PASSWORD:-imagentx_pass}
      
      # 应用配置
      SERVER_PORT: 8088
      FRONTEND_PORT: 3000
      NEXT_PUBLIC_API_BASE_URL: /api
      
      # Spring 配置
      SPRING_PROFILES_ACTIVE: prod
      JPA_DDL_AUTO: update
      SHOW_SQL: false
      
      # 用户配置 - 使用直接环境变量注入，确保配置能正确读取
      IMAGENTX_ADMIN_EMAIL: ${IMAGENTX_ADMIN_EMAIL:-admin@imagentx.ai}
      IMAGENTX_ADMIN_PASSWORD: ${IMAGENTX_ADMIN_PASSWORD:-admin123}
      IMAGENTX_ADMIN_NICKNAME: ${IMAGENTX_ADMIN_NICKNAME:-Imagent X管理员}
      IMAGENTX_TEST_ENABLED: ${IMAGENTX_TEST_ENABLED:-false}
      IMAGENTX_TEST_EMAIL: ${IMAGENTX_TEST_EMAIL:-test@imagentx.ai}
      IMAGENTX_TEST_PASSWORD: ${IMAGENTX_TEST_PASSWORD:-test123}
      IMAGENTX_TEST_NICKNAME: ${IMAGENTX_TEST_NICKNAME:-测试用户}
      
      # 消息队列配置
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-guest}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-guest}
      
      # 安全配置
      JWT_SECRET: ${JWT_SECRET:-please_change_this_in_production}
      
      # 日志配置
      LOG_LEVEL_ROOT: warn
      LOG_LEVEL_APP: info
      
      # 文件存储
      FILE_STORAGE_PATH: /app/storage
      
    volumes:
      - storage-data:/app/storage
    ports:
      - "${HTTP_PORT:-3000}:3000"
    networks:
      - imagentx-network
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s