version = 5.0.0
archive_dir = /etc/letsencrypt/archive/imagentx.top
cert = /etc/letsencrypt/live/imagentx.top/cert.pem
privkey = /etc/letsencrypt/live/imagentx.top/privkey.pem
chain = /etc/letsencrypt/live/imagentx.top/chain.pem
fullchain = /etc/letsencrypt/live/imagentx.top/fullchain.pem
[renewalparams]
account = d0e7a1cd6bf9304823c8742f17c76296
authenticator = dns-cloudflare
dns_cloudflare_propagation_seconds = 120
dns_cloudflare_credentials = /etc/letsencrypt/cloudflare.ini
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
