# 开发环境配置文件 - 使用H2内存数据库
# 此配置文件完全覆盖主配置文件中的数据库设置

server:
  port: 8088
  servlet:
    context-path: /api

spring:
  application:
    name: Imagent X
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: sa
    password: password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 1
        max-concurrency: 2
        prefetch: 1
        acknowledge-mode: manual
        default-requeue-rejected: true
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: org.xhy.domain
  type-handlers-package: org.xhy.infrastructure.converter
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted_at
      logic-delete-value: now()
      logic-not-delete-value: "null"
    banner: false

# 禁用需要外部依赖的功能
high-availability:
  enabled: false

embedding:
  enabled: false
  name: disabled
  vector-store:
    enabled: false

logging:
  level:
    root: info
    org.xhy: debug
    org.springframework.web: debug
    org.hibernate.SQL: debug
