server:
  port: 8088
  servlet:
    context-path: /api

spring:
  application:
    name: Imagent X
  
  # H2数据库配置
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: sa
    password: password
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  
  # H2控制台
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # 数据库初始化
  sql:
    init:
      mode: always
      schema-locations: classpath:db/migration/*.sql
      data-locations: classpath:db/rag_tables.sql
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  # RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
        acknowledge-mode: manual
        default-requeue-rejected: true
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000
      direct:
        acknowledge-mode: manual
        default-requeue-rejected: true
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000
    publisher-returns: true
    publisher-confirm-type: correlated
    connection-timeout: 200000
    cache:
      channel:
        size: 25

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: org.xhy.domain
  type-handlers-package: org.xhy.infrastructure.converter
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted_at
      logic-delete-value: now()
      logic-not-delete-value: "null"
    banner: false

# 监控端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: info
    org.xhy: debug
    org.springframework.web: debug
    org.hibernate.SQL: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

